const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const nodes=new Map();
function node(id){if(!nodes.has(id)){const classes=new Set();nodes.set(id,{style:{},dataset:{},hidden:false,open:false,textContent:'',innerHTML:'',classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x),toggle:(x,on)=>on?classes.add(x):classes.delete(x)},before(){},setAttribute(){},querySelectorAll(){return[]},getContext(){return{}},addEventListener(){},showModal(){this.open=true},close(){this.open=false},parentElement:{setAttribute(){}}});}return nodes.get(id);}
let now=1000;
const context={assert,console,Date,Math,performance:{now:()=>now},requestAnimationFrame(){},setInterval(){},localStorage:{getItem(){return null},setItem(){}},window:{addEventListener(){}},document:{hidden:false,body:node('body'),createElement:()=>node('new'),getElementById:node,querySelector:node,querySelectorAll:()=>[],addEventListener(){}}};
vm.createContext(context);for(const f of ['curriculum.js','app.js','quick-run.js'])vm.runInContext(fs.readFileSync(`${__dirname}/../dist/${f}`,'utf8'),context);
const run=code=>vm.runInContext(code,context);
function tick(ms){for(let n=0;n<ms;n+=20){now+=20;run(`quickTick(${now})`);}}
run(`saved.sound=false; startQuickRun();assert.equal(quickRun.state,'intro');assert.equal(quickRun.remaining,Infinity);showQuickQuestion();assert.equal(quickRun.limit,6000);assert.equal(quickRun.choices.length,4);assert.equal(new Set(quickRun.choices).size,4);toggleQuickPause();var before=quickRun.remaining;var world=quickRun.clock;`);
tick(2500);run(`assert.equal(quickRun.remaining,before);assert.equal(quickRun.clock,world);toggleQuickPause();quickRun.pace='arcade';showQuickQuestion();assert.equal(quickRun.limit,2000);`);
tick(2020);run(`assert.equal(quickRun.state,'correction');assert.equal(saved.xp,0);assert.equal(quickRun.retry.length,1);assert.equal(quickRun.remaining,Infinity);`);
run(`toggleQuickPause();startLesson(0);assert.equal(quickRun,null);assert.equal($('lesson-content').classList.contains('quick-paused'),false);for(const w of COURSE[0].words)saved.memory[w[0]]={streak:1,due:0};startQuickRun();assert.equal(quickRun.limit,2000);var actualRoad=quickRun.road;quickRun.road=actualRoad.map(l=>({...l,type:'grass'}));`);
for(let d=0;d<4;d++){run(`player={x:3,y:3};showQuickQuestion();quickRun.correctDirection=${d};quickRun.choices[${d}]=quickRun.word[0];var old={...player};chooseQuick(${d});assert.equal(player.x,old.x+DIRECTIONS[${d}].dx);assert.equal(player.y,old.y+DIRECTIONS[${d}].dy);var xp=saved.xp;chooseQuick(${d});assert.equal(saved.xp,xp);`);tick(180);}
run(`var directionsSeen=new Set();player={x:3,y:3};for(let n=0;n<1000;n++)directionsSeen.add(chooseDirection());assert.equal(directionsSeen.size,4);player={x:0,y:0};for(let n=0;n<100;n++){let d=chooseDirection();assert(d===1||d===2);}quickRun.road=actualRoad;var carLane=quickRun.road[1];var car=laneObjects(carLane,0).find(o=>o.x>=0&&o.x<=6);assert(unsafeAt(car.x,1,0));var water=quickRun.road[4];var log=laneObjects(water,0).find(o=>o.x>=0&&o.x<=6);assert(!unsafeAt(log.x,4,0));assert(unsafeAt(log.x+water.spacing/2,4,0));assert(unsafeAt(-1,3,0));`);
run(`quickRun.state='question';player={x:car.x,y:1};var lives=quickRun.lives;roadCollision();assert.equal(quickRun.lives,lives-1);assert.equal(player.y,quickRun.checkpoint.y);assert.equal(quickRun.state,'correction');roadCollision();assert.equal(quickRun.lives,lives-1);`);
run(`startQuickRun();quickRun.road=quickRun.road.map(l=>({...l,type:'grass'}));quickRun.pace='untimed';showQuickQuestion();assert.equal(quickRun.limit,Infinity);`);
for(let n=0;n<20;n++){run(`assert.equal(quickRun.state,'question');quickRun.correctDirection=1;quickRun.choices[1]=quickRun.word[0];chooseQuick(1);`);tick(180);}
run(`assert.equal(player.y,20);assert.equal(quickRun.state,'complete');assert.equal(quickRun.correct,20);assert.equal(saved.completed.length,0);startLesson(0);for(let n=0;n<6;n++){phase='question';render();assert(answer(word()[0]).correct);finishCrossing();$('next-crossing').onclick();}assert(checkpoint);for(let n=0;n<6;n++){assert(answer(word()[0]).correct);$('checkpoint-next').onclick();}assert(saved.completed.includes(0));assert(startLesson(1));`);
console.log('PASS: four directional moves, answer variety, boundaries, timers, pause, timeout retry, cars, logs/water, collision/checkpoint/life handling, duplicate input, 20-row completion, and guided course unlock.');
